# Site
repository: seungjohan/korea
favicon: images/favicon.ico

# Personal info
name: Seungjo Han
title: Junior Product Manger
email: seungjohan.kr@gmail.com
website: https://seungjohan.github.io/korea
website_title: KOR Resume

phone: +82 010-9908-6439


# Social links
linkedin_username: seungjohan

# twitter_username: konnellwaldron
github_username:  seungjohan
# dribbble_username: jekyll
# facebook_username: hhieut
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb

# Additional icon links
additional_links:
- title: medium
  icon: "fab fa-medium" # Change Medium logo to "fa-brands fa-medium" later
  url: https://medium.com/failurestories
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Seungjo Han

  I try constantly to challenge myself.<br/>
  Experiences in business, software engineering, communication, and leadership have enabled me to become the professional I am today.<br/>
  My main goal is to leave my mark in line with my personal ideas, drawing on my past experiences to promote the ongoing expansion of innovation in the company.

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# Projects Section
projects_title: Projects

# Relevant Activities
relevantactivity_title: Relevant Activities


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 주제로 발표와 기고, 출판을 해왔습니다.
   - [우아콘2020 - 수십억건에서 Querydsl 사용하기](https://www.youtube.com/watch?v=zMAX7g6rO_Y)
   - [스프링 부트와 AWS로 혼자 구현하는 웹 서비스](https://jojoldu.tistory.com/463)
   - [EO 인터뷰](https://www.youtube.com/watch?v=V9AGvwPmnZU&t=2s)
   - [2019 우아한 스프링 배치](https://www.youtube.com/watch?v=_nkJkWVH-mo&t=14s)
   - [인프런 - IntelliJ IDEA 가이드](https://www.inflearn.com/course/intellij-guide)
   - [2018 KCD - IntelliJ IDEA만으로 개발하기](https://www.youtube.com/watch?v=wBXSUdT1jX0)
   - [2018 JetBrains Day - Upsource를 이용한 코드리뷰](https://www.youtube.com/watch?v=06bJt6CnRAU&feature=youtu.be)
   - [마소 394호 - AWS EC2와 TravisCI를 활용한 무중단 배포 서비스](http://it.chosun.com/site/data/html_dir/2018/10/29/2018102900482.html)
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
